### ISSUE TITLE
Styling for login page created

### ISSUE THREAD

**Issue by shiyadliger** [shiyadliger/LearnCoding#4]
Looking to style the login page using css to create a aesthetically appealing to users.

**Comment by SHIYADBAVA** [comment]
Will do the styling part to make the login page more attractive to the end user. There by proving the users with better user experience.

**Comment by shiyadliger** [comment]
Styling of login page made the website much better than the average looking html skeleton.

**Comment by shiyadliger** [comment]
Issue closed as the development looking better.
